### ISSUE TITLE
why warnings?

### ISSUE THREAD

**Issue by fireartist** [monken/p5-moosex-chainedaccessors#2]
Hi,
I've converted Catalyst::Controller::HTML::FormFu to use MooseX::ChainedAccessors, and am unsure why I'm getting warnings.
All code which uses the 'Chained' trait does an explicit "use MooseX::ChainedAccessors;" [1]
But every test file issues a warning, like so:
t/01basic-form.t ................. Implicit use of the Chained trait is deprecated. Please load MooseX::Attribute::Chained explicitly at /home/cafranks/perl5/perlbrew/perls/perl-5.12.3/lib/site_perl/5.12.3/Moose/Meta/Attribute/Custom/Trait/Chained.pm line 19.
The docs (synopsis) doesn't show an explicit use of anything, and the test file chained.t does
use_ok('MooseX::Attribute::Chained');
use_ok('MooseX::ChainedAccessors::Accessor');
use_ok('MooseX::Traits::Attribute::Chained');
- but the last 2 of those are deprecated, so I don't think I would need to be `use`ing them.
  What am I doing wrong?

[1] https://github.com/fireartist/Catalyst-Controller-HTML-FormFu/commit/e767d695f3573ca2c365be5ce03c29f6cc2de4aa

perl 5.12.3
Moose 2.06.03
MooseX::Attribute::Chained 1.0.1

**Comment by monken** [comment]
You need to `use MooseX::Attribute::Chained` and not MooseX::ChanedAccessors

**Comment by monken** [comment]
This needs to be loaded prior to any attribute loading the "Chained" trait.
